server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.52.129:3306/zim?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  devtools:
    restart:
      #设置开启热部署
      enabled: true
  mvc:
    #静态资源访问路径
    static-path-pattern: /**
  resources:
    #静态资源映射路径
    static-locations: classpath:/static
  redis:
    database: 0
    host: 192.168.52.129
    port: 6379
    password: 123456
    timeout: 2000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  cache.type: redis
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.asm.zim.server.entry
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
im:
  ip: 192.168.52.1
  tcp:
    start: true
    #默认 8888
    port: 7777
    boss-thread-count: 1
    work-thread-count: 8
    queue-count: 128
    keepalive: true
  websocket:
    start: true
    #默认 9999
    port: 8888
    boss-thread-count: 1
    work-thread-count: 8
    #默认 128
    queue-count: 128
    #默认true
    keepalive: true
    #默认 512 * 1024
    http-max-length: 514288
    #默认 10 * 1024 * 1024
    max-frame-aggregator: 10485760
    #默认 100 * 1024 * 1024
    frame-max-length: 104857600
  aop:
    around-log: false
  file-server:
    url: http://192.168.52.129:7070
  #是否开启自动 检查过期channelMap
  check-channel-map: false
  token-encrypt: false
  session-expire-time: 3000
logging:
  level:
    root: info

